import "../styles/globals.css";

import { AuthProvider } from "@/contexts/AuthContext";
import { Bangers } from "next/font/google";
import type { Metadata } from "next";
import { ProjectProvider } from "@/contexts/ProjectContext";
import { Toaster } from "react-hot-toast";

const bangers = Bangers({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-hero",
});

export const metadata: Metadata = {
  title: "Hero Force 🦸‍♂️",
  description: "Generated by Gabriel C Medeiros 🎨🖌️",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bangers.variable} font-hero`}>
        <AuthProvider>
          <ProjectProvider>
            {children}
          </ProjectProvider>
        </AuthProvider>
        <Toaster position="top-right" toastOptions={{ duration: 3000 }} />
      </body>
    </html>
  );
}
