import "./globals.css";

import { Bangers } from "next/font/google";
import type { Metadata } from "next";

const bangers = Bangers({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-hero",
});

export const metadata: Metadata = {
  title: "Hero Force 🦸‍♂️",
  description: "Generated by Gabriel C Medeiros 🎨🖌️",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bangers.variable} font-hero`}>
        {children}
      </body>
    </html>
  );
}
