version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hero-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heroforce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: hero-backend
    command: npm run start:dev 
    volumes:
      - .:/app 
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: heroforce
      JWT_SECRET: devsecret
      JWT_EXPIRES: 3600s
    ports:
      - "3000:3000"

volumes:
  postgres_data:
